/* Auto-generated by inject-config.js at build time. Do not edit manually. */
const CONFIG = {
  SUPABASE_URL: 'https://dmvogtovtvwnakrqqfwc.supabase.co',
  SUPABASE_KEY: 'sb_publishable_TgoHH_kM8jPaqekxwoWGgw_vYWW94PX',
};
