/* ============================================
   inject-config.js — Build Script
   ============================================
   Runs at Vercel build time.
   Reads environment variables and writes them
   into config.js so the browser can access them.

  Required Vercel environment variables:
    SUPABASE_URL
    SUPABASE_KEY
  Optional (server-side only):
    ANTHROPIC_KEY
   ============================================ */

const fs = require('fs');

function readLocalEnvFile() {
  const out = {};
  if (!fs.existsSync('.env.local')) return out;

  const lines = fs.readFileSync('.env.local', 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx <= 0) continue;
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim();
    out[key] = val;
  }
  return out;
}

const localEnv = readLocalEnvFile();
const supabaseUrl = process.env.SUPABASE_URL || localEnv.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_KEY || localEnv.SUPABASE_KEY || '';
if (!supabaseUrl || !supabaseKey) {
  console.warn('⚠️  Warning: SUPABASE_URL or SUPABASE_KEY not set.');
}

const configContent = `/* Auto-generated by inject-config.js at build time. Do not edit manually. */
const CONFIG = {
  SUPABASE_URL: '${supabaseUrl}',
  SUPABASE_KEY: '${supabaseKey}',
};
`;

fs.writeFileSync('config.js', configContent);
console.log('✅ config.js generated successfully.');
